### ISSUE TITLE
pls ignores the proxy set with the https_proxy variable

### ISSUE THREAD

**Issue by hashworks** [papertigers/plex-list#1]
At one of my networks I'm behind a firewall and need to use a HTTP proxy to connect to the internet. For that I set environment variables in my shell, like:

```
$ env | grep proxy
no_proxy=127.0.0.1,localhost,.foobar,10.0.0.0/8
http_proxy=http://webproxy.foobar:8080
https_proxy=http://webproxy.foobar:8080
ftp_proxy=http://webproxy.foobar:8080
all_proxy=http://webproxy.foobar:8080
NO_PROXY=127.0.0.1,localhost,.foobar,10.0.0.0/8
FTP_PROXY=http://webproxy.foobar:8080
HTTPS_PROXY=http://webproxy.foobar:8080
HTTP_PROXY=http://webproxy.foobar:8080
ALL_PROXY=http://webproxy.foobar:8080
```

However, pls seems to ignore those:
```
error: https://tautulli.foo.bar/api/v2?apikey=...&cmd=get_activity: error trying to connect: Connection refused (os error 111)
```

**Comment by papertigers** [comment]
Thanks for the report.  I haven't added any proxy support, but I could probably wire it up so that it's a command line option (including env and config). I will look into doing this if you are still interested.

**Comment by join3r** [comment]
There is probably a different problem here.
System proxy support should work by default as per https://docs.rs/reqwest/0.10.4/reqwest/index.html#proxies

**Comment by papertigers** [comment]
The current version of reqwest should be something like v0.11.10
I would be interested in knowing if this issue is still present for you.


Just a quick test on my end using localhost as a "broken" https proxy, and it seems to fail and then work correctly without it.

```
❯ HTTPS_PROXY=127.0.0.1 pls
error: error sending request for url (https://plexpy.foobar.com:/api/v2?apikey=APIKEY&cmd=get_activity): error trying to connect: tcp connect error: Connection refused (os error 61)
```

```txt
❯ pls
┌─────────────────────────────────────┐
│ 🎵 Stay Outside - From Indian Lakes │
└─────────────────────────────────────┘
    State: paused
    User: USER
    Player: iPhone (iOS)
    Quality: Original
    Container: mp3
    Progress: [─────────◼─]
    IP: 🔒IP-ADDR
```

**Comment by hashworks** [comment]
`master` seems to work on my end. Issue can then be closed with a new release.

**Comment by papertigers** [comment]
The latest version should already be good to go! 
Thanks for the initial report.
